# .github/workflows/docs-preview.yml
name: Docs Preview

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx

      - name: Build docs
        run: sphinx-build docs/ _build/html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: _build/html
