# .github/workflows/docs-preview.yml
name: Sphinx Docs Preview

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme

      - name: Build Sphinx HTML docs
        run: sphinx-build -b html docs/ _build/html

      - name: Upload Sphinx HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: sphinx-docs-html
          path: _build/html
