# .github/workflows/docs-preview.yml
name: Docs Preview

on:
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build sphinx terms
        uses: ammaraskar/sphinx-action@7.0.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx

      - name: Build docs
        run: sphinx-build docs/ _build/html

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: sphinx-docs
          path: _build/html
