name: "Export terms to POEditor"
on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build sphinx terms
      uses: ammaraskar/sphinx-action@35082eb35b69713fe335801c4d5846a4cc3c91ff
      env:
        GITHUB_ACTIONS: 1
      with:
        docs-folder: "./"
        pre-build-command: "apt-get update -y && apt-get install -y pandoc"
        build-command: "sphinx-build -b gettext . _build"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poeditor
    - name: Upload terms
      env:
        POEDITOR_API_TOKEN: ${{ secrets.POEDITOR_API_TOKEN }}
        POEDITOR_PROJECT_ID: "432737"
      run: |
        python upload_terms.py
